<?php
/**
 * Created by PhpStorm.
 * User: nik
 * Date: 14.07.18
 * Time: 20:01
 */

namespace Views;

use System\Main\Core;

class BaseMenuView extends BaseView {

    private $allBottles;
    private $allWorkedDevices;
    private $todayBottles;
    private $newBarcodes;
    private $allErrors;

    /**
     * @param mixed $allBottles
     */
    public function setAllBottles($allBottles)
    {   
        $this->allBottles = $allBottles;
    }

    /**
     * @param mixed $allWorkedDevices
     */
    public function setAllWorkedDevices($allWorkedDevices)
    {
        $this->allWorkedDevices = $allWorkedDevices;
    }

    /**
     * @param mixed $todayBottles
     */
    public function setTodayBottles($todayBottles)
    {
        $this->todayBottles = $todayBottles;
    }

    /**
     * @param mixed $newBarcodes
     */
    public function setNewBarcodes($newBarcodes)
    {
        $this->newBarcodes = $newBarcodes;
    }

    /**
     * @param mixed $allErrors
     */
    public function setAllErrors($allErrors)
    {
        $this->allErrors = $allErrors;
    }




    public function getPageName(){
        return "";
    }

    public function drawMenu()
    {
        $page = $this->getPageName();
        ?>
        <div class="menu-wrapper">
            <div id="menu-container">
                <?if($page == "devices"){?>
                    <div class="menu-item menu-item-selected">Устройства</div>
                <?}else{?>
                    <div onclick="location.href='/devices'" class="menu-item">Устройства</div>
                <?}?>

                <!-- <?if($page == "barcodes"){?>
                    <div class="menu-item menu-item-selected">Штрих-коды</div>
                <?}else{?>
                    <div onclick="location.href='/barcodes'" class="menu-item">Штрих-коды</div>
                <?}?>

                <?if($page == "coupons"){?>
                    <div class="menu-item menu-item-selected">Купоны</div>
                <?}else{?>
                    <div onclick="location.href='/coupons'" class="menu-item">Купоны</div>
                <?}?> -->

                <?if($page == "users"){?>
                    <div class="menu-item menu-item-selected">Пользователи</div>
                <?}else{?>
                    <div onclick="location.href='/users'" class="menu-item">Пользователи</div>
                <?}?>

                <div class="menu-info">
                    <span id="user-name"><?=Core::getInstance()->getUser()->getLogin();?></span>
                    <i onclick="logout()" class="fas fa-sign-out-alt icon"></i>
                </div>
            </div>
        </div>
        <?
    }

    public function scriptLoad()
    {
        parent::scriptLoad(); // TODO: Change the autogenerated stub
        ?>
        <script src="<?=$this->assets("js/menu/logout.js");?>"></script>
        <script src="<?=$this->assets("js/menu/menu.js");?>"></script>
        <?

    }

}