<?php
/**
 * Created by PhpStorm.
 * User: nik
 * Date: 28.02.19
 * Time: 20:21
 */

namespace Views;


class EmptyMessageView extends BaseView
{

    private $message;
    private $script;

    /**
     * @param mixed $script
     */
    public function setScript($script)
    {
        $this->script = $script;
    }



    /**
     * @param mixed $message
     */
    public function setMessage($message)
    {
        $this->message = $message;
    }



    public function drawContent()
    {
        ?>
        <h1 class="h1-error"><?=$this->message?></h1>
        <?
    }

    public function scriptLoad()
    {
        parent::scriptLoad(); // TODO: Change the autogenerated stub
        ?>
        <script><?=$this->script?></script>
        <?
    }
}